# Generated by Django 4.2.6 on 2023-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=30)),
            ],
        ),
    ]
